config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :create, :new] do
    resources :doses, only: [:new, :create, :show]
  end
  resources :doses, only: [:destroy]
  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new(dose_params)
      @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.find(params[:id])
  end


  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<!-- <h1>Cocktails</h1> -->

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1516481025691-ba0f3e6d43b4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c27a03efea95e481e6befb649d5db144&auto=format&fit=crop&w=1650&q=80');">
  <div class="banner-content">
    <h1>Cocktails</h1>
    <p>view or upload a cocktail below</p>
  </div>
</div>

 <div class="container">
  <% @cocktails.each do |cocktail| %>
    <div class="row card">
      <div class="col-xs-12 col-sm-4 card-description">
        <h2> <%= link_to cocktail.name, cocktail_path(cocktail), class: "card-description" %>  </h2>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1> <%= @cocktail.name %> </h1>

<%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail) %>


<div>
  <h2>Doses</h2>
  <ul>
    <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.description %> <%= dose.ingredient.name %>
      [<%= link_to "Delete dose", dose_path(dose), method: :delete %>]
    </li>
    <% end %>
  </ul>
</div>



<%= link_to "Back to Cocktails", cocktails_path %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.input :description %>
<%= f.association :ingredient, collection: Ingredient.all %>
<%= f.submit %>
<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

<%= render "form", dose: @dose, cocktail: @cocktail %>

app/views/doses/new.html.erb
<h1><%= @cocktail.name %></h1>
<p>Add ingredients for <%= @cocktail.name %></p>

<%= render "form", dose: @dose, cocktail: @cocktail %>


<div class: back-btn > <%= link_to "back", cocktail_path(@cocktail) %> </div>

app/views/doses/show.html.erb
<p>hello</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>